services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - writable_data:/var/www/html/writable
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4pgk
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  writable_data:
